POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "leonel",
  "firstName": "Leonel",
  "lastName": "Zorzoli",
  "email": "zorzolileonel@gmail.com",
  "country": "Argentina",
  "password": "leonel"
}